version:  '3.7'
services:
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "8888:80"
    depends_on:
      - fpm

  fpm:
    container_name: cars_fpm
    build:
      context: .
      dockerfile: fpm/Dockerfile
    restart: on-failure
    working_dir: /var/www/app
    volumes:
      - '..:/var/www/app'

  mysql:
    image: mysql:latest
    container_name: mysql_carnovo
    volumes:
      - "../.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carnovo
      MYSQL_USER: default
      MYSQL_PASSWORD: default