version:  '3.7'
services:
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "8888:80"
    depends_on:
      - fpm

  fpm:
    container_name: cars_fpm
    build:
      context: .
      dockerfile: fpm/Dockerfile
    restart: on-failure
    working_dir: /var/www/app
    volumes:
      - '..:/var/www/app'